#spring.application.name=restaurantListing
#server.port=9091
#spring.datasource.url=jdbc:mysql://localhost:3306/
#spring.datasource.username=root
#spring.datasource.password=root


  # Db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurentdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

# register with eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


